const products = [
  {
    "id": 1,
    "category": "Electronics",
    "image": "https://m.media-amazon.com/images/I/61PDbUd1VaL._SL1500_.jpg",
    "productName": "Samsung Galaxy Buds FE",
    "brandName": "Samsung",
    "price": 7999,
    "rating": 4.4,
    "productCarbonWeight": 6.8,
    "productUrl": "https://www.amazon.in/dp/B0CJZ5SCVZ",
  },
  {
    "id": 2,
    "category": "Electronics",
    "image": "https://m.media-amazon.com/images/I/71bhWgQK-cL._SL1500_.jpg",
    "productName": "JBL Tune 760NC Wireless Headphones",
    "brandName": "JBL",
    "price": 5999,
    "rating": 4.3,
    "productCarbonWeight": 7.9,
    "productUrl": "https://www.amazon.in/dp/B097RDVJ4L",
  },
  {
    "id": 3,
    "category": "Electronics",
    "image": "https://m.media-amazon.com/images/I/61oTnA6k5jL._SL1500_.jpg",
    "productName": "Noise ColorFit Ultra 3 Smartwatch",
    "brandName": "Noise",
    "price": 2499,
    "rating": 4.1,
    "productCarbonWeight": 5.3,
    "productUrl": "https://www.amazon.in/dp/B0C6M8NXWS",
  },

  {
    "id": 4,
    "category": "Fashion",
    "image": "https://m.media-amazon.com/images/I/81T1ZBQZQ5L._SL1500_.jpg",
    "productName": "Levi's Men's Slim Jeans",
    "brandName": "Levi's",
    "price": 1899,
    "rating": 4.2,
    "productCarbonWeight": 12.4,
    "productUrl": "https://www.amazon.in/dp/B07HKVCF9H",
  },
  {
    "id": 5,
    "category": "Fashion",
    "image": "https://m.media-amazon.com/images/I/61o0hSLB5-L._SL1500_.jpg",
    "productName": "Nike Men's Revolution 6 Shoes",
    "brandName": "Nike",
    "price": 2999,
    "rating": 4.5,
    "productCarbonWeight": 9.5,
    "productUrl": "https://www.amazon.in/dp/B09X671FQ9",
  },
  {
    "id": 6,
    "category": "Fashion",
    "image": "https://m.media-amazon.com/images/I/61xJQeVpKRL._SL1500_.jpg",
    "productName": "Adidas Men’s T-Shirt",
    "brandName": "Adidas",
    "price": 899,
    "rating": 4.2,
    "productCarbonWeight": 8.2,
    "productUrl": "https://www.amazon.in/dp/B08ZN3F3PF",
  },

  {
    "id": 7,
    "category": "Beauty",
    "image": "https://m.media-amazon.com/images/I/61IM7jTAt3L._SL1500_.jpg",
    "productName": "Mamaearth Vitamin C Face Wash",
    "brandName": "Mamaearth",
    "price": 249,
    "rating": 4.3,
    "productCarbonWeight": 2.2,
    "productUrl": "https://www.amazon.in/dp/B085FYNQ9D",
  },
  {
    "id": 8,
    "category": "Beauty",
    "image": "https://m.media-amazon.com/images/I/61zJ1tO4PkL._SL1500_.jpg",
    "productName": "Maybelline Fit Me Foundation",
    "brandName": "Maybelline",
    "price": 399,
    "rating": 4.4,
    "productCarbonWeight": 3.1,
    "productUrl": "https://www.amazon.in/dp/B00PFCT3Y6",
  },
  {
    "id": 9,
    "category": "Beauty",
    "image": "https://m.media-amazon.com/images/I/6166i5I9dFL._SL1500_.jpg",
    "productName": "L'Oréal Paris Shampoo 1L",
    "brandName": "L'Oréal",
    "price": 799,
    "rating": 4.2,
    "productCarbonWeight": 4.5,
    "productUrl": "https://www.amazon.in/dp/B089WZC5FN",
  },

  {
    "id": 10,
    "category": "Books",
    "image": "https://m.media-amazon.com/images/I/71KilybDOoL._SL1500_.jpg",
    "productName": "Atomic Habits",
    "brandName": "James Clear",
    "price": 399,
    "rating": 4.7,
    "productCarbonWeight": 3.4,
    "productUrl": "https://www.amazon.in/dp/1847941834",
  },
  {
    "id": 11,
    "category": "Books",
    "image": "https://m.media-amazon.com/images/I/81bsw6fnUiL._SL1500_.jpg",
    "productName": "The Subtle Art of Not Giving a F*ck",
    "brandName": "Mark Manson",
    "price": 350,
    "rating": 4.6,
    "productCarbonWeight": 3.2,
    "productUrl": "https://www.amazon.in/dp/0062457713",
  },
  {
    "id": 12,
    "category": "Books",
    "image": "https://m.media-amazon.com/images/I/71aFt4+OTOL._SL1500_.jpg",
    "productName": "The Alchemist",
    "brandName": "Paulo Coelho",
    "price": 299,
    "rating": 4.6,
    "productCarbonWeight": 3.1,
    "productUrl": "https://www.amazon.in/dp/8172234988",
  },

  {
    "id": 13,
    "category": "Home & Kitchen",
    "image": "https://m.media-amazon.com/images/I/61u1a8Z+9qL._SL1500_.jpg",
    "productName": "Philips HL7756/00 Mixer Grinder",
    "brandName": "Philips",
    "price": 3499,
    "rating": 4.3,
    "productCarbonWeight": 22.5,
    "productUrl": "https://www.amazon.in/dp/B0756Z43QS",
  },
  {
    "id": 14,
    "category": "Home & Kitchen",
    "image": "https://m.media-amazon.com/images/I/71hr4UwsvTL._SL1500_.jpg",
    "productName": "Milton Thermosteel Flask 1L",
    "brandName": "Milton",
    "price": 899,
    "rating": 4.4,
    "productCarbonWeight": 9.1,
    "productUrl": "https://www.amazon.in/dp/B01N6E2JPV",
  },
  {
    "id": 15,
    "category": "Home & Kitchen",
    "image": "https://m.media-amazon.com/images/I/71QpGLoAl-L._SL1500_.jpg",
    "productName": "Pigeon Electric Kettle 1.5L",
    "brandName": "Pigeon",
    "price": 649,
    "rating": 4.1,
    "productCarbonWeight": 6.2,
    "productUrl": "https://www.amazon.in/dp/B078KJH7M5",
  },

  {
    "id": 16,
    "category": "Sports",
    "image": "https://m.media-amazon.com/images/I/81eVcTj7eUL._SL1500_.jpg",
    "productName": "Nivia Storm Football",
    "brandName": "Nivia",
    "price": 699,
    "rating": 4.3,
    "productCarbonWeight": 4.2,
    "productUrl": "https://www.amazon.in/dp/B00IYH4XMI",
  },
  {
    "id": 17,
    "category": "Sports",
    "image": "https://m.media-amazon.com/images/I/81l4j7MCR2L._SL1500_.jpg",
    "productName": "Yonex GR 303 Badminton Racquet",
    "brandName": "Yonex",
    "price": 499,
    "rating": 4.2,
    "productCarbonWeight": 3.6,
    "productUrl": "https://www.amazon.in/dp/B00K1QMXTC",
  },
  {
    "id": 18,
    "category": "Sports",
    "image": "https://m.media-amazon.com/images/I/81auFfhbUSL._SL1500_.jpg",
    "productName": "Boldfit Yoga Mat",
    "brandName": "Boldfit",
    "price": 799,
    "rating": 4.3,
    "productCarbonWeight": 3.1,
    "productUrl": "https://www.amazon.in/dp/B085KTZ6F9",
  },

  {
    "id": 19,
    "category": "Toys",
    "image": "https://m.media-amazon.com/images/I/81tq9WZPz3L._SL1500_.jpg",
    "productName": "Lego Classic Bricks Set",
    "brandName": "LEGO",
    "price": 3499,
    "rating": 4.8,
    "productCarbonWeight": 5.9,
    "productUrl": "https://www.amazon.in/dp/B00NHQF6MG",
  },
  {
    "id": 20,
    "category": "Toys",
    "image": "https://m.media-amazon.com/images/I/81jwLtRIuBL._SL1500_.jpg",
    "productName": "Rubik's Cube 3x3",
    "brandName": "Rubik's",
    "price": 299,
    "rating": 4.6,
    "productCarbonWeight": 1.9,
    "productUrl": "https://www.amazon.in/dp/B00000JRCQ",
  },

  {
    "id": 21,
    "category": "Grocery",
    "image": "https://m.media-amazon.com/images/I/71ZL4ZkWc5L._SL1500_.jpg",
    "productName": "Tata Tea Premium 1kg",
    "brandName": "Tata",
    "price": 480,
    "rating": 4.5,
    "productCarbonWeight": 2.7,
    "productUrl": "https://www.amazon.in/dp/B00HAE3X3K",
  },
];
